### ISSUE TITLE
Why Event for OnDataReceived ???

### ISSUE THREAD

**Issue by dnxit** [sethcall/async-helper#1]
Why not return the parsed(or byte[]) response in the same function SendAsync like a normal service call function ???

its normal for a service call that you pass parameters and get a response back

**Comment by sethcall** [comment]
TCP is a data transport, not a service.

There is no contract like in a service call or API. You can send or receive whatever you like, whenever you like.

Based on your question, I'm thinking perhaps you are not looking at the right project for your needs.

Hope that helps,
Seth

**Comment by dnxit** [comment]
what if for every send I must get a receive ? I just want to avoid the event 
because it need a subscription and then un-subscription to dispose the object properly

**Comment by sethcall** [comment]
Hi there,

You need to look at HTTP, REST APIs, etc. 

This library helps you communicate at the TCP layer, which is a 2-way, asynchronous communication mechanism that let's you devise your own protocol on top.

  It sounds like you don't want the extra baggage that entails.   Use HTTP.

**Comment by dnxit** [comment]
I've a specific requirement to use TCP but the usage will be like a service call. that's why I was thinking to use AsyncTcpClient to send data and then receive the response in the same function like a normal function e.g.
Task<Account> GetAccount(string accountNumber);

**Comment by sethcall** [comment]
You won't get that out of the box anywhere that I can think of.

HTTP is built on top of TCP, of course.   I don't  know your requirements,
but building a new protocol when one suffices already and has tons of
tooling sounds like a waste in most situations.

**Comment by sethcall** [comment]
If you need two-way, async communication between two processes, consider
something like Apache Thrift. You will get your request/response or
something much closer to it, with much less work on your part.
https://thrift.apache.org/

**Comment by sethcall** [comment]
@dnxit I'm closing this issue.  I understand what you want, but it's not within the scope to do what you are looking to do with this library.  Hope the pointers above help!
